AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Step Function Template

##########################################################################
#   Parameters
#   https://docs.aws.amazon.com/ko_kr/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html
##########################################################################
Parameters:
  DefaultName:
    Type: String
    Default: sample
  PythonVersion:
    Type: String
    Default: python3.8
  StageType:
    Type: String
    Default: dev

##########################################################################
#   Globals
#   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
##########################################################################
Globals:
  Function:
    Runtime: !Sub ${PythonVersion}
    MemorySize: 3072
    Timeout: 900
    Layers:
      # - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:layer이름:버전(숫자)
      - !Ref SampleSharedLayer
    Tags:
      ServiceType: !Sub ${ServiceType}
    AutoPublishAlias: !Ref StageType
    VpcConfig:
      SecurityGroupIds:
        - sg-00000000000000000
      SubnetIds:
        - subnet-00000000000000000
        - subnet-11111111111111111

Resources:
  ##########################################################################
  #   AWS::Serverless::Function
  #   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-resource-function.html
  ##########################################################################
  Lambda01Task:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${DefaultName}-Lambda01Task
      Description: !Sub ${DefaultName}-Lambda01Task
      Tags:
        Name: !Sub ${DefaultName}-Lambda01Task
      CodeUri: template/step_functions/EXPRESS/functions/lambda_01_task
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${LambdaRole}
  Lambda02Map01Task:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${DefaultName}-Lambda02Map01Task
      Description: !Sub ${DefaultName}-Lambda02Map01Task
      Tags:
        Name: !Sub ${DefaultName}-Lambda02Map01Task
      CodeUri: template/step_functions/EXPRESS/functions/lambda_02_map_01_task
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${LambdaRole}
  Lambda03Task:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${DefaultName}-Lambda03Task
      Description: !Sub ${DefaultName}-Lambda03Task
      Tags:
        Name: !Sub ${DefaultName}-Lambda03Task
      CodeUri: template/step_functions/EXPRESS/functions/lambda_03_task
      Handler: app.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${LambdaRole}
  ##########################################################################
  #   AWS::Serverless::StateMachine
  #   https://docs.aws.amazon.com/ko_kr/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  ##########################################################################
  SampleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Name: !Sub ${StageType}-${DefaultName}-StateMachine
      Tags:
        Name: !Sub ${StageType}-${DefaultName}-StateMachine
        ServicType: !Sub ${ServiceType}
      Role: !ImportValue sample-iam:StepFunctionsRoleArn # iam/template.yml 참고
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt SampleStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL #ERROR
      DefinitionUri: template/step_functions/EXPRESS/statemachine/step_function.asl.json
      DefinitionSubstitutions:
        Lambda01TaskArn: !GetAtt Lambda01Task.Arn
        Lambda02Map01TaskArn: !GetAtt Lambda02Map01Task.Arn
        Lambda03TaskArn: !GetAtt Lambda03Task.Arn
  # StepFunction 로그
  SampleStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/states/${StageType}-${DefaultName}-StateMachine
      RetentionInDays: 30
